name: Run Failure Example

on: workflow_dispatch

jobs:
  example-failure:
    name: Integration Sanity Check
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@master
      - uses: './'
        with:
          path: './test/integration/bad.md'
          rulesets: 'textlint-rule-alex textlint-rule-common-misspellings textlint-rule-en-capitalization textlint-rule-no-empty-section textlint-rule-no-exclamation-question-mark textlint-rule-one-sentence-per-line textlint-rule-period-in-list-item textlint-rule-spelling textlint-rule-terminology textlint-rule-write-good dictionary-en'
        